// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"book-management/internal/controller/ping"
	"book-management/internal/route"
)

// Injectors from wire.go:

func InitializeApp() *App {
	middleWareSet := route.NewGlobalMiddlewareSet()
	pingController := ping.NewPingController()
	webHandlerSet := route.NewWebHandlerSet(pingController)
	engine := route.NewRouter(middleWareSet, webHandlerSet)
	app := newApp(engine)
	return app
}
